Import Debian changes 253.5-ok1

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -3,24 +3,17 @@
 set -e
 
 _systemctl() {
-    if [ -d /run/systemd/system ]; then
+    if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
         systemctl "$@"
     fi
 }
 
 _update_catalog() {
-    journalctl --update-catalog || true
+    journalctl ${DPKG_ROOT:+--root="$DPKG_ROOT"} --update-catalog || true
 }
 
 _update_binfmt() {
-    # If binfmt-support is installed and active do not restart
-    # systemd-binfmt.service. It will unregister all currently registered
-    # binary formats in ExecStop and not all packages with a binfmt-support
-    # configuration ship a corresponding binfmt.d snippet yet.
-    # Once this is the case, this additional safety check can be removed.
-    if ! _systemctl -q is-active binfmt-support.service; then
-        _systemctl try-restart systemd-binfmt.service || true
-    fi
+    _systemctl try-restart systemd-binfmt.service || true
 }
 
 # Update Message Catalogs database and binfmt registrations in response to dpkg triggers
@@ -41,76 +34,25 @@ fi
 
 # Enable getty and remote-fs.target by default on new installs
 if [ -z "$2" ]; then
-    systemctl enable getty@tty1.service || true
-    systemctl enable remote-fs.target || true
-fi
-
-# Enable resolved by default on new installs installs and upgrades
-if dpkg --compare-versions "$2" lt "234-1ubuntu2~"; then
-    systemctl enable systemd-resolved.service || true
-fi
-
-# Drop stock /etc/rc.local on upgrades
-if dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
-        if [ -f /etc/rc.local ]; then
-                if [ "10fd9f051accb6fd1f753f2d48371890" = "$(md5sum /etc/rc.local | cut -d\  -f1)" ]; then
-                        echo Removing empty /etc/rc.local
-                        rm -f /etc/rc.local || true
-                fi
-        fi
+    systemctl ${DPKG_ROOT:+--root="$DPKG_ROOT"} enable getty@tty1.service || true
+    systemctl ${DPKG_ROOT:+--root="$DPKG_ROOT"} enable remote-fs.target || true
 fi
 
 # Enable systemd-pstore by default on new installs and upgrades, see #952767
 if dpkg --compare-versions "$2" lt "245.4-4~"; then
-    systemctl enable systemd-pstore.service || true
+    systemctl ${DPKG_ROOT:+--root="$DPKG_ROOT"} enable systemd-pstore.service || true
 fi
 
 # Create /etc/machine-id
-systemd-machine-id-setup
+systemd-machine-id-setup ${DPKG_ROOT:+--root="$DPKG_ROOT"}
 
-# Setup system users and groups
-addgroup --quiet --system systemd-journal
-
-adduser --quiet --system --group --no-create-home --home /run/systemd \
-    --gecos "systemd Network Management" systemd-network
-
-# Enable persistent journal, in auto-mode, by default on new installs installs and upgrades
-if dpkg --compare-versions "$2" lt "235-3ubuntu3~"; then
-    mkdir -p /var/log/journal
-    # create tmpfiles only when running systemd, otherwise %b substitution fails
-    if [ -d /run/systemd/system ]; then
-        systemd-tmpfiles --create --prefix /var/log/journal
-    fi
+# Enable persistent journal, in auto-mode, by default on new installs and upgrades
+if dpkg --compare-versions "$2" lt "244.1-2~"; then
+    mkdir -p "$DPKG_ROOT/var/log/journal"
 fi
 
 # Initial update of the Message Catalogs database
 _update_catalog
-
-# Disable networkd when upgrading from broken versions 8..10. Turns out
-# enabling networkd unconditionally has long boot time side-effects
-if dpkg --compare-versions "$2" gt "234-2ubuntu8~" &&
-   dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
-    systemctl disable systemd-networkd-wait-online.service || true
-fi
-
-# skip daemon-reexec and try-restarts during shutdown to avoid hitting LP: #1803391
-if [ -n "$2" ] && [ "$(systemctl is-system-running)" != "stopping" ]; then
-    _systemctl daemon-reexec || true
-    # do not restart logind; this can be done again once this gets implemented:
-    # https://github.com/systemd/systemd/issues/1163
-    if dpkg --compare-versions "$2" lt-nl "246.2-2~"; then
-        # the socket configuration changed
-        _systemctl stop systemd-networkd.socket || true
-    fi
-    _systemctl try-restart systemd-networkd.service || true
-    _systemctl try-restart systemd-journald.service || true
-fi
-
-# Process all tmpfiles that we ship, including any overrides in
-# runtime-dir/sysadmin-dir/other packages (e.g. rsyslog)
-#
-# Ignore if this fails, because e.g. %b will fail on WSL
-systemd-tmpfiles --create || :
 
 if dpkg --compare-versions "$2" lt-nl "245.4-4~"; then
     # systemd-pstore.service is now enabled via sysinit.target
@@ -123,4 +65,44 @@ if dpkg --compare-versions "$2" lt-nl "245.4-5~"; then
     rm -f /etc/systemd/system/multi-user.target.wants/ondemand.service
 fi
 
+# Move the old locale file into /etc. Symlinks will be created by tmpfiles.d later
+if [ -f /etc/default/locale ] && [ ! -L /etc/default/locale ] && [ ! -f /etc/locale.conf ]; then
+    mv /etc/default/locale /etc/locale.conf
+fi
+
+# Process all tmpfiles that we ship, including any overrides in
+# runtime-dir/sysadmin-dir/other packages (e.g. rsyslog)
+#
+# Ignore if this fails, because e.g. %b will fail on WSL
+systemd-tmpfiles --create || :
+
 #DEBHELPER#
+
+# skip daemon-reexec and try-restarts during shutdown to avoid hitting LP: #1803391
+if [ -n "$2" ] && [ "$(systemctl is-system-running)" != "stopping" ]; then
+    # LP: #2013543 - the systemd cmdline can get mangled depending on the
+    # contents of /proc/cmdline, which causes systemd to fail to deserialize
+    # it's previous state on daemon-reexec. This means that for upgrades from
+    # affected versions, we need a reboot and cannot re-exec here, else the
+    # bug could be triggered.
+    if dpkg --compare-versions "$2" lt "249.11-0ubuntu3.10~" ||
+        dpkg --compare-versions "$2" eq "252.5-2ubuntu3" ||
+        dpkg --compare-versions "$2" eq "253.5-1ubuntu1"; then
+        if ! grep -Fqsx systemd /run/reboot-required.pkgs; then
+            echo systemd >> /run/reboot-required.pkgs || true
+        fi
+
+        # Reload to avoid warnings when restarting services below
+        _systemctl daemon-reload || true
+    else
+        _systemctl daemon-reexec || true
+    fi
+    # do not restart logind
+    # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919509
+    if dpkg --compare-versions "$2" lt-nl "246.2-2~"; then
+        # the socket configuration changed
+        _systemctl stop systemd-networkd.socket || true
+    fi
+    _systemctl try-restart systemd-networkd.service || true
+    _systemctl try-restart systemd-journald.service || true
+fi
